// actions for authentication
export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE';
export const SIGN_UP = 'SIGN_UP';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const SIGN_UP_FAILURE = 'SIGN_UP_FAILURE';
export const START_PROCESSING = 'START_PROCESSING';
export const FINISH_PROCESSING = 'FINISH_PROCESSING';
export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_FORGOT_PASSWORD = 'AUTH_FORGOT_PASSWORD';
export const AUTH_FORGOT_PASSWORD_COMPLETE = 'AUTH_FORGOT_PASSWORD_COMPLETE';
export const AUTH_RESET_PASSWORD = 'AUTH_RESET_PASSWORD';
export const AUTH_RESET_PASSWORD_COMPLETE = 'AUTH_RESET_PASSWORD_COMPLETE';
export const ERROR_PROCESSING = 'ERROR_PROCESSING';

//action get user info
export const GET_USER_PROFILE_INFO = 'GET_USER_PROFILE_INFO';
export const GET_USER_PROFILE_INFO_SUCCESS = 'GET_USER_PROFILE_INFO_SUCCESS';
export const GET_USER_PROFILE_INFO_FAILUE = 'GET_USER_PROFILE_INFO_FAILUE';
export const PATH_UPDATE_PROFILE = 'PATH_UPDATE_PROFILE';
export const PATH_UPDATE_PROFILE_SUCCESS = 'PATH_UPDATE_PROFILE_SUCCESS';
export const PATH_UPDATE_PROFILE_FAILUE = 'PATH_UPDATE_PROFILE_FAILUE';


//action get threads
export const GET_THREAD_LIST = 'GET_THREAD_LIST';
export const GET_THREAD_LIST_SUCCESS = 'GET_THREAD_LIST_SUCCESS';
export const GET_THREAD_LIST_FAIL = 'GET_THREAD_LIST_FAIL';
export const GET_THREAD_LIST_START = 'GET_THREAD_LIST_START';

//action update threads
export const ADD_TO_THREAD_LIST = 'ADD_TO_THREAD_LIST';
export const UPDATE_THREAD_LIST = 'UPDATE_THREAD_LIST';
export const UPDATE_TAG_THREAD = 'UPDATE_TAG_THREAD';
export const UPDATE_LIKE_STATUS = 'UPDATE_LIKE_STATUS';


// search action
export const SEARCH_ALL = 'SEARCH_ALL';
export const SEARCH_START = 'SEARCH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILURE = 'SEARCH_FAILURE';
export const CLEAR_SEARCH_RESULT = 'CLEAR_SEARCH_RESULT';
