json.id @post.id
json.hiding_creator @post.hiding_creator
json.body @post.body
json.body_raw @post.body_raw
json.body_search @post.body_search
json.poster_type @post.poster_type
json.created_at @post.created_at
json.updated_at @post.updated_at
json.author @post.author
json.likes @post.likers